import scrapy
from scrapy.crawler import CrawlerProcess


class ThivienAuthorListSpider(scrapy.Spider):
    name = "thivien_author_list"
    
    # URL trang danh sách tác giả (Page 4)
    start_urls = [
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=50",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=52",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=52&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=52&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=52&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=52&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=52&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=53",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=53&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=54",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=55",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=BirthYear&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Country&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Page=1&Sort=Views&SortOrder=desc",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Views&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Date&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=55&Sort=Poster&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=56",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=56&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=56&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=57",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=BirthYear&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Country&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&Page=1&SortOrder=desc",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Views&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=7", 
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Date&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=57&Sort=Poster&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=BirthYear&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Country&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&Page=1&SortOrder=desc",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Views&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Date&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=2&Sort=Poster&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age%5B%5D=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=BirthYear&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Country&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Views&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Date&SortOrder=desc&Page=10",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=1",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=2",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=3",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=4",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=5",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=6",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=7",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=8",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=9",
        "https://www.thivien.net/search-author.php?Country=2&Age[]=3&Sort=Poster&Page=10",
    ]

    custom_settings = {
        'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'ROBOTSTXT_OBEY': True,
        'DOWNLOAD_DELAY': 5,
    }
    count = 0

    def parse(self, response):
        # Lặp qua từng khối item chứa thông tin tác giả
        # Class "list-item" bao bọc toàn bộ thông tin của 1 dòng
        for item in response.css('.list-item'):
            
            # Tìm thẻ <a> bên trong thẻ <h4 class="list-item-header">
            author_link = item.css('.list-item-header a')
            
            name = author_link.css('::text').get()
            href = author_link.css('::attr(href)').get()

            # Chỉ lấy dữ liệu nếu tìm thấy cả tên và link
            if name and href:
                print(f"TAC GIA: {name} - Link: {href}")
                self.count += 1
                yield {
                    'tác giả': name.strip(),
                    'url': response.urljoin(href) # Chuyển link tương đối thành tuyệt đối
                }
                if self.count % 100 == 0:
                    print(f"Đã thu thập được {self.count} tác giả.")
                    import time
                    time.sleep(300)  # Tạm dừng 2 giây sau mỗi 50 tác giả thu thập được

# --- Cấu hình chạy trực tiếp ---
if __name__ == "__main__":
    process = CrawlerProcess(settings={
        'FEEDS': {
            'authors_list.json': { # Tên file output
                'format': 'json',
                'encoding': 'utf8',
                'indent': 4,
                'overwrite': True,
            }
        },
        'LOG_LEVEL': 'INFO'
    })

    process.crawl(ThivienAuthorListSpider)
    process.start()